### ISSUE TITLE
Amazon Kindle Fire 5th Gen is not unlocked when auto-rotate is off

### ISSUE THREAD

**Issue by anupchaudhari01** [bbc/device_api-android#100]
When running Hive test on Amazon Kindle Fire 5th Gen, the screen does not get unlocked automatically. We have to manually unlock screen in order to test PASS. But when checked with Asim, he suggested me to enable the auto-rotate on device and try and it worked.

So It seems that the Hive doesn't unlock device when auto-rotate is disabled on device.

**Comment by jonpwilson** [comment]
Hello,

A new version of the DeviceAPI::Android gem has been released; [version 1.2.9](https://rubygems.org/gems/device_api-android/versions/1.2.9) should fix the issues you've seen with not unlocking a kindle correctly.

Thanks,

Jon
