### ISSUE TITLE
Total Memory for kindle devices is always returned as nil

### ISSUE THREAD

**Issue by Asimk21** [bbc/device_api-android#58]
The regex  `/(.*):\s+(.*)\s+\(.*\)/`does not return Total RAM (Observed in Kindle). It should be replaced by `/(.*):\s+(.*)\s+(.*)/`, but it needs cross check on other devices as well

**Comment by Asimk21** [comment]
/(.*):\s+(.*)\s+(.*)/ works for samsung-sm-g920f

**Comment by jonpwilson** [comment]
In the current form, it only captures two groups but this will get 3. Do we need to capture the third group?

**Comment by Asimk21** [comment]
This regex `/(.*):\s+(.*)\s/` returns two groups now (tested with both Kindle KFTHWI and samsung-sm-g920f)
