### ISSUE TITLE
Need to be able to reboot a device and check for it to become available again

### ISSUE THREAD

**Issue by jonpwilson** [bbc/device_api-android#63]
If you use ADB to restart a device you should be able to keep a handle on that device and wait for it to become responsive (will possibly require a 'restarting' state adding)

**Comment by jitgo** [comment]
I've used this in the past to wait for devices to become responsive before continuing with tests etc and has worked on pretty much every device reliably: 

`adb -s $device_ip wait-for-device shell 'while [ "`getprop dev.bootcomplete`" != "1" ]; do sleep 1;printf .; done'`

**Comment by jrmhaig** [comment]
Part of bbc/hive-runner#154
Linked to bbc/hive-runner-android#17

**Comment by Asimk21** [comment]
#118

**Comment by Asimk21** [comment]
Closed via #118
