### ISSUE TITLE
netcfg removed in Android 6

### ISSUE THREAD

**Issue by jonpwilson** [bbc/device_api-android#92]
The netcfg command has been removed and replaced with ifconfig. This means that the 'get_network_info' method won't work and instead returns ```/system/bin/sh: netcfg: not found``` and so no IP address or Wifi MAC address is returned. 

We can either support version specific commands (i.e. os version < 6 use netcfg; os version >= 6 use ifconfig) or try to find a method for returning the network info on all versions.

**Comment by mayurkukadiya0** [comment]
I have also same problem. I want to find my device's ip address, but can't find it...
